window.env = {
  NEXT_PUBLIC_FIREBASE_API_KEY: "AIzaSyAonG1_DBWPP-_tyzlm7GmpoYCSDpcHlgA",
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "aztec-karaoke.firebaseapp.com",
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: "aztec-karaoke",
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "aztec-karaoke.firebasestorage.app",
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "653086043635",
  NEXT_PUBLIC_FIREBASE_APP_ID: "1:653086043635:web:18ad66bd7a1c61aa67b686"
};